name: Run new-release script TRY

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version to release"
        required: true
        default: "0.62.0"

jobs:
  generate_diffs:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup asdf
        uses: asdf-vm/actions/setup@v1

      - name: Cache asdf
        uses: actions/cache@v3
        with:
          path: |
            /home/runner/.asdf
          key: ${{ runner.os }}-asdf-${{ hashFiles('**/.tool-versions') }}
          restore-keys: |
            ${{ runner.os }}-asdf-

      - name: asdf install
        uses: asdf-vm/actions/install@v1

      - name: yarn install
        run: yarn install

      - name: Run new-release script
        run: echo wow
