name: Run new-release script

on:
  repository_dispatch:
    types: [publish]

jobs:
  generate_diffs:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: asdf install
        uses: asdf-vm/actions/install@v1

      - name: yarn install
        run: yarn install

      - name: Run new-release script
        run: ./new-release.sh ${{ github.event.client_payload.version }}
